In [77]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline

In [78]:
train_df = pd.read_csv('titanic_train.csv')
train = pd.read_csv('titanic_train.csv')
test_df = pd.read_csv('titanic_test.csv')

In [79]:
import tensorflow as tf
import keras 
from keras.layers import Dense, Dropout, Input
from keras.models import Sequential

In [80]:
train_df.drop(['Cabin', 'PassengerId', 'Ticket', 'Name'], axis='columns', inplace=True)
test_passenger_id = test_df.PassengerId
test_df.drop(['Cabin', 'PassengerId', 'Ticket', 'Name'], axis='columns', inplace=True)

In [81]:
train_df.Age.fillna(train_df.Age.mean(), inplace=True)
train_df.Embarked.fillna('C', inplace=True)
test_df.Age.fillna(test_df.Age.mean(), inplace=True)
test_df.Embarked.fillna('C', inplace=True)
test_df.Fare.fillna(test_df.Fare.mean(), inplace=True)

In [82]:
sex_categorical = pd.get_dummies(train_df.Sex)
train_df['Male'] = sex_categorical.male
train_df['Female'] = sex_categorical.female
train_df.drop('Sex', axis='columns', inplace=True)

train_df.head()

   Survived  Pclass   Age  SibSp  Parch     Fare Embarked  Male  Female
0         0       3  22.0      1      0   7.2500        S     1       0
1         1       1  38.0      1      0  71.2833        C     0       1
2         1       3  26.0      0      0   7.9250        S     0       1
3         1       1  35.0      1      0  53.1000        S     0       1
4         0       3  35.0      0      0   8.0500        S     1       0

In [83]:
pclass_categorical = pd.get_dummies(train_df.Pclass)
train_df['Pclass1'] = pclass_categorical[1]
train_df['Pclass2'] = pclass_categorical[2]
train_df['Pclass3'] = pclass_categorical[3]
train_df.drop('Pclass', axis='columns', inplace=True)

train_df.head()

,Survived,Age,SibSp,Parch,Fare,Embarked,Male,Female,Pclass1,Pclass2,Pclass3
0,0,22.0,1,0,7.2500,S,1,0,0,0,1
1,1,38.0,1,0,71.2833,C,0,1,1,0,0
2,1,26.0,0,0,7.9250,S,0,1,0,0,1
3,1,35.0,1,0,53.1000,S,0,1,1,0,0
4,0,35.0,0,0,8.0500,S,1,0,0,0,1

In [84]:
embarked_categorical = pd.get_dummies(train_df.Embarked)
train_df['EmbarkedC'] = embarked_categorical.C
train_df['EmbarkedQ'] = embarked_categorical.Q
train_df['EmbarkedS'] = embarked_categorical.S
train_df.drop('Embarked', axis='columns', inplace=True)

train_df.head()

,Survived,Age,SibSp,Parch,Fare,Male,Female,Pclass1,Pclass2,Pclass3,EmbarkedC,EmbarkedQ,EmbarkedS
0,0,22.0,1,0,7.2500,1,0,0,0,1,0,0,1
1,1,38.0,1,0,71.2833,0,1,1,0,0,1,0,0
2,1,26.0,0,0,7.9250,0,1,0,0,1,0,0,1
3,1,35.0,1,0,53.1000,0,1,1,0,0,0,0,1
4,0,35.0,0,0,8.0500,1,0,0,0,1,0,0,1

In [85]:
from sklearn.preprocessing import minmax_scale
train_df['Age'] = pd.Series(minmax_scale(train_df['Age']), index=train_df.index)
train_df['SibSp'] = pd.Series(minmax_scale(train_df['SibSp']), index=train_df.index)
train_df['Parch'] = pd.Series(minmax_scale(train_df['Parch']), index=train_df.index)
train_df['Fare'] = pd.Series(minmax_scale(train_df['Fare']), index=train_df.index)

train_df.head()

,Survived,Age,SibSp,Parch,Fare,Male,Female,Pclass1,Pclass2,Pclass3,EmbarkedC,EmbarkedQ,EmbarkedS
0,0,0.271174,0.125,0.0,0.014151,1,0,0,0,1,0,0,1
1,1,0.472229,0.125,0.0,0.139136,0,1,1,0,0,1,0,0
2,1,0.321438,0.000,0.0,0.015469,0,1,0,0,1,0,0,1
3,1,0.434531,0.125,0.0,0.103644,0,1,1,0,0,0,0,1
4,0,0.434531,0.000,0.0,0.015713,1,0,0,0,1,0,0,1

In [86]:
target_df = train_df.Survived
train_df.drop('Survived', axis='columns', inplace=True)

In [87]:
X = train_df.to_numpy()
Y = target_df.to_numpy()
Y = Y.reshape(Y.size, 1)

In [88]:
print(X.shape)
print(Y.shape)

(891, 12)
(891, 1)

Creating Neural Network

In [89]:
import tensorflow as tf
import keras 
from keras.layers import Dense, Dropout, Input
from keras.models import Sequential

In [90]:
# Initialising the NN
model = Sequential()

# layers
model.add(Dense(units = 9, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
model.add(Dense(units = 9, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(units = 5, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN
model.fit(X, Y, batch_size = 32, epochs = 200)

Epoch 1/200
28/28 [==============================] - 1s 3ms/step - loss: 0.6917 - accuracy: 0.6162
Epoch 2/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6881 - accuracy: 0.6162
Epoch 3/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6790 - accuracy: 0.6162
Epoch 4/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6565 - accuracy: 0.6162
Epoch 5/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6132 - accuracy: 0.6162
Epoch 6/200
28/28 [==============================] - 0s 2ms/step - loss: 0.5669 - accuracy: 0.6162
Epoch 7/200
28/28 [==============================] - 0s 3ms/step - loss: 0.5443 - accuracy: 0.6891
Epoch 8/200
28/28 [==============================] - 0s 2ms/step - loss: 0.5325 - accuracy: 0.8025
Epoch 9/200
28/28 [==============================] - 0s 3ms/step - loss: 0.5227 - accuracy: 0.8126
Epoch 10/200
28/28 [==============================] - 0s 2ms/step - loss: 0.5114 - accuracy: 0.8159
Epoch 11/200
28/28 [==============================] - 0s 2ms/step - loss: 0.5018 - accuracy: 0.8126
Epoch 12/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4908 - accuracy: 0.8137
Epoch 13/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4825 - accuracy: 0.7946
Epoch 14/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4740 - accuracy: 0.8114
Epoch 15/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4670 - accuracy: 0.8126
Epoch 16/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4608 - accuracy: 0.7980
Epoch 17/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4566 - accuracy: 0.7991
Epoch 18/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4516 - accuracy: 0.8114
Epoch 19/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4483 - accuracy: 0.8103
Epoch 20/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4457 - accuracy: 0.8114
Epoch 21/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4425 - accuracy: 0.8148
Epoch 22/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4405 - accuracy: 0.8103
Epoch 23/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4396 - accuracy: 0.8148
Epoch 24/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4390 - accuracy: 0.8092
Epoch 25/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4370 - accuracy: 0.8103
Epoch 26/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4362 - accuracy: 0.8159
Epoch 27/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4377 - accuracy: 0.8092
Epoch 28/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4346 - accuracy: 0.8092
Epoch 29/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4340 - accuracy: 0.8137
Epoch 30/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4338 - accuracy: 0.8148
Epoch 31/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4346 - accuracy: 0.8126
Epoch 32/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4337 - accuracy: 0.8148
Epoch 33/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4358 - accuracy: 0.8171
Epoch 34/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4328 - accuracy: 0.8159
Epoch 35/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4327 - accuracy: 0.8171
Epoch 36/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4317 - accuracy: 0.8193
Epoch 37/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4319 - accuracy: 0.8159
Epoch 38/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4322 - accuracy: 0.8137
Epoch 39/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4318 - accuracy: 0.8137
Epoch 40/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4309 - accuracy: 0.8148
Epoch 41/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4305 - accuracy: 0.8171
Epoch 42/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4320 - accuracy: 0.8159
Epoch 43/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4307 - accuracy: 0.8159
Epoch 44/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4306 - accuracy: 0.8171
Epoch 45/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4313 - accuracy: 0.8137
Epoch 46/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4319 - accuracy: 0.8137
Epoch 47/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4305 - accuracy: 0.8171
Epoch 48/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4308 - accuracy: 0.8159
Epoch 49/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4308 - accuracy: 0.8126
Epoch 50/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4296 - accuracy: 0.8148
Epoch 51/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4304 - accuracy: 0.8159
Epoch 52/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4297 - accuracy: 0.8159
Epoch 53/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4301 - accuracy: 0.8171
Epoch 54/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4297 - accuracy: 0.8126
Epoch 55/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4304 - accuracy: 0.8193
Epoch 56/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4303 - accuracy: 0.8182
Epoch 57/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4299 - accuracy: 0.8159
Epoch 58/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4297 - accuracy: 0.8171
Epoch 59/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4297 - accuracy: 0.8182
Epoch 60/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4287 - accuracy: 0.8182
Epoch 61/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4288 - accuracy: 0.8159
Epoch 62/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4293 - accuracy: 0.8171
Epoch 63/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4284 - accuracy: 0.8159
Epoch 64/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4289 - accuracy: 0.8171
Epoch 65/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4294 - accuracy: 0.8159
Epoch 66/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4287 - accuracy: 0.8171
Epoch 67/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4281 - accuracy: 0.8148
Epoch 68/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4286 - accuracy: 0.8193
Epoch 69/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4297 - accuracy: 0.8204
Epoch 70/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4287 - accuracy: 0.8171
Epoch 71/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4288 - accuracy: 0.8137
Epoch 72/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4281 - accuracy: 0.8148
Epoch 73/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4296 - accuracy: 0.8126
Epoch 74/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4283 - accuracy: 0.8171
Epoch 75/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4281 - accuracy: 0.8182
Epoch 76/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4284 - accuracy: 0.8193
Epoch 77/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4280 - accuracy: 0.8137
Epoch 78/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4283 - accuracy: 0.8182
Epoch 79/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4294 - accuracy: 0.8182
Epoch 80/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4283 - accuracy: 0.8193
Epoch 81/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4280 - accuracy: 0.8182
Epoch 82/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4282 - accuracy: 0.8159
Epoch 83/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4276 - accuracy: 0.8227
Epoch 84/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4282 - accuracy: 0.8182
Epoch 85/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4276 - accuracy: 0.8148
Epoch 86/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4280 - accuracy: 0.8159
Epoch 87/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4270 - accuracy: 0.8193
Epoch 88/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4281 - accuracy: 0.8171
Epoch 89/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4264 - accuracy: 0.8182
Epoch 90/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4279 - accuracy: 0.8159
Epoch 91/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4273 - accuracy: 0.8204
Epoch 92/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4271 - accuracy: 0.8148
Epoch 93/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4271 - accuracy: 0.8227
Epoch 94/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4266 - accuracy: 0.8171
Epoch 95/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4265 - accuracy: 0.8171
Epoch 96/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4264 - accuracy: 0.8193
Epoch 97/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4262 - accuracy: 0.8193
Epoch 98/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4270 - accuracy: 0.8159
Epoch 99/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4265 - accuracy: 0.8182
Epoch 100/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4265 - accuracy: 0.8204
Epoch 101/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4258 - accuracy: 0.8215
Epoch 102/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4262 - accuracy: 0.8159
Epoch 103/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4268 - accuracy: 0.8182
Epoch 104/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4257 - accuracy: 0.8159
Epoch 105/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4255 - accuracy: 0.8171
Epoch 106/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4254 - accuracy: 0.8159
Epoch 107/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4260 - accuracy: 0.8182
Epoch 108/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4266 - accuracy: 0.8204
Epoch 109/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4255 - accuracy: 0.8159
Epoch 110/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4256 - accuracy: 0.8227
Epoch 111/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4268 - accuracy: 0.8137
Epoch 112/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4254 - accuracy: 0.8171
Epoch 113/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4262 - accuracy: 0.8193
Epoch 114/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4258 - accuracy: 0.8182
Epoch 115/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4249 - accuracy: 0.8204
Epoch 116/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4267 - accuracy: 0.8193
Epoch 117/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4258 - accuracy: 0.8204
Epoch 118/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4252 - accuracy: 0.8193
Epoch 119/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4259 - accuracy: 0.8171
Epoch 120/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4265 - accuracy: 0.8182
Epoch 121/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4249 - accuracy: 0.8215
Epoch 122/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4256 - accuracy: 0.8159
Epoch 123/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4242 - accuracy: 0.8193
Epoch 124/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4246 - accuracy: 0.8204
Epoch 125/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4246 - accuracy: 0.8193
Epoch 126/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4249 - accuracy: 0.8193
Epoch 127/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4241 - accuracy: 0.8193
Epoch 128/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4244 - accuracy: 0.8215
Epoch 129/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4249 - accuracy: 0.8148
Epoch 130/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4244 - accuracy: 0.8204
Epoch 131/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4248 - accuracy: 0.8171
Epoch 132/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4247 - accuracy: 0.8182
Epoch 133/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4251 - accuracy: 0.8137
Epoch 134/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4245 - accuracy: 0.8159
Epoch 135/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4253 - accuracy: 0.8148
Epoch 136/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4260 - accuracy: 0.8182
Epoch 137/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4248 - accuracy: 0.8171
Epoch 138/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4238 - accuracy: 0.8204
Epoch 139/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4238 - accuracy: 0.8193
Epoch 140/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4238 - accuracy: 0.8204
Epoch 141/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4240 - accuracy: 0.8204
Epoch 142/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4241 - accuracy: 0.8193
Epoch 143/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4238 - accuracy: 0.8159
Epoch 144/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4240 - accuracy: 0.8260
Epoch 145/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4236 - accuracy: 0.8182
Epoch 146/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4240 - accuracy: 0.8193
Epoch 147/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4241 - accuracy: 0.8182
Epoch 148/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4236 - accuracy: 0.8204
Epoch 149/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4236 - accuracy: 0.8159
Epoch 150/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4242 - accuracy: 0.8215
Epoch 151/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4237 - accuracy: 0.8159
Epoch 152/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4235 - accuracy: 0.8182
Epoch 153/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4236 - accuracy: 0.8193
Epoch 154/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4232 - accuracy: 0.8193
Epoch 155/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4235 - accuracy: 0.8171
Epoch 156/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4234 - accuracy: 0.8193
Epoch 157/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4227 - accuracy: 0.8182
Epoch 158/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4233 - accuracy: 0.8159
Epoch 159/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4235 - accuracy: 0.8171
Epoch 160/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4236 - accuracy: 0.8159
Epoch 161/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4228 - accuracy: 0.8171
Epoch 162/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4228 - accuracy: 0.8148
Epoch 163/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4235 - accuracy: 0.8204
Epoch 164/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4229 - accuracy: 0.8159
Epoch 165/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4224 - accuracy: 0.8193
Epoch 166/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4241 - accuracy: 0.8159
Epoch 167/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4237 - accuracy: 0.8193
Epoch 168/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4230 - accuracy: 0.8204
Epoch 169/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4225 - accuracy: 0.8159
Epoch 170/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4229 - accuracy: 0.8137
Epoch 171/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4229 - accuracy: 0.8215
Epoch 172/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4228 - accuracy: 0.8227
Epoch 173/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4229 - accuracy: 0.8238
Epoch 174/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4224 - accuracy: 0.8171
Epoch 175/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4226 - accuracy: 0.8148
Epoch 176/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4223 - accuracy: 0.8204
Epoch 177/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4230 - accuracy: 0.8215
Epoch 178/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4230 - accuracy: 0.8193
Epoch 179/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4225 - accuracy: 0.8159
Epoch 180/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4229 - accuracy: 0.8182
Epoch 181/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4234 - accuracy: 0.8159
Epoch 182/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4232 - accuracy: 0.8114
Epoch 183/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4224 - accuracy: 0.8171
Epoch 184/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4226 - accuracy: 0.8193
Epoch 185/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4218 - accuracy: 0.8215
Epoch 186/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4225 - accuracy: 0.8193
Epoch 187/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4223 - accuracy: 0.8182
Epoch 188/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4225 - accuracy: 0.8204
Epoch 189/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4238 - accuracy: 0.8126
Epoch 190/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4228 - accuracy: 0.8148
Epoch 191/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4217 - accuracy: 0.8171
Epoch 192/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4225 - accuracy: 0.8193
Epoch 193/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4219 - accuracy: 0.8171
Epoch 194/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4224 - accuracy: 0.8193
Epoch 195/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4220 - accuracy: 0.8204
Epoch 196/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4223 - accuracy: 0.8148
Epoch 197/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4218 - accuracy: 0.8137
Epoch 198/200
28/28 [==============================] - 0s 2ms/step - loss: 0.4222 - accuracy: 0.8193
Epoch 199/200
28/28 [==============================] - 0s 3ms/step - loss: 0.4223 - accuracy: 0.8193

In [95]:
X_test = test_df.to_numpy()